TEMPLATE	= app
CONFIG		+= qt warn_on release
DESTDIR		= ../bin
HEADERS		= snake.h target.h obstacle.h interface.h codes.h
SOURCES		= snake.cpp target.cpp obstacle.cpp interface.cpp main.cpp
TARGET		= snake
INCLUDEPATH	+= ../library
DEPENDPATH	+= ../library
LIBS            += -lqpe
