TEMPLATE	= app
CONFIG		+= qt warn_on release
DESTDIR		= ../../bin
HEADERS		= settime.h
SOURCES		= settime.cpp main.cpp
INCLUDEPATH	+= ../../library
DEPENDPATH	+= ../../library
LIBS            += -lqpe
TARGET		= systemtime 
